### ISSUE TITLE
Rework Scale 'DropDown'

### ISSUE THREAD

**Issue by andreashille** [TNG/next-generation-scrum-poker#103]
![grafik](https://user-images.githubusercontent.com/46956485/220446857-00b2a6bb-b450-4f63-836a-02c5732ee17d.png)
 currently in different browsers the 'Change Scale' behaves strange (one reasons is, that the hidden selected disabled properties are interpreted differently depending on browser and os see immage Chrome @ Intel Mac )

**Comment by lukastaegert** [comment]
Maybe it is time for a non-native dropdown?

**Comment by ThiloAschebrock** [comment]
Fixing this bug should hopefully also fix the flickering of the selector on a scale change, which is only visible in the production build.
